---
name: build
on:
  push:
  # schedule:
  # - cron: 0 2 1,15 * *

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

      # build the mods
    - name: build minelittlepony
      run: node .github/buildmod minelittlepony/minelittlepony minelp
    - name: build hdskins
      run: node .github/buildmod minelittlepony/hdskins hdskins

    - name: upload mods
      uses: actions/upload-artifact@v2
      with:
        name: mods
        path: mods
